// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/miroswan/mesops/pkg/v1/allocator/allocator.proto

/*
Package allocator is a generated protocol buffer package.

It is generated from these files:
	github.com/miroswan/mesops/pkg/v1/allocator/allocator.proto

It has these top-level messages:
	InverseOfferStatus
*/
package allocator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos "github.com/miroswan/mesops/pkg/v1/mesos"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InverseOfferStatus_Status int32

const (
	// We have not received a response yet. This is the default state before
	// receiving a response.
	InverseOfferStatus_UNKNOWN InverseOfferStatus_Status = 1
	// The framework is ok with the inverse offer. This means it will not
	// violate any SLAs and will attempt to evacuate any tasks running on the
	// agent. If the tasks are not evacuated by the framework, the operator can
	// manually shut down the slave knowing that the framework will not have
	// violated its SLAs.
	InverseOfferStatus_ACCEPT InverseOfferStatus_Status = 2
	// The framework wants to block the maintenance operation from happening. An
	// example would be that it cannot meet its SLA by losing resources.
	InverseOfferStatus_DECLINE InverseOfferStatus_Status = 3
)

var InverseOfferStatus_Status_name = map[int32]string{
	1: "UNKNOWN",
	2: "ACCEPT",
	3: "DECLINE",
}
var InverseOfferStatus_Status_value = map[string]int32{
	"UNKNOWN": 1,
	"ACCEPT":  2,
	"DECLINE": 3,
}

func (x InverseOfferStatus_Status) Enum() *InverseOfferStatus_Status {
	p := new(InverseOfferStatus_Status)
	*p = x
	return p
}
func (x InverseOfferStatus_Status) String() string {
	return proto.EnumName(InverseOfferStatus_Status_name, int32(x))
}
func (x *InverseOfferStatus_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InverseOfferStatus_Status_value, data, "InverseOfferStatus_Status")
	if err != nil {
		return err
	}
	*x = InverseOfferStatus_Status(value)
	return nil
}
func (InverseOfferStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// *
// Describes the status of an inverse offer.
//
// This is a protobuf so as to be able to share the status to inverse offers
// through endpoints such as the maintenance status endpoint.
type InverseOfferStatus struct {
	Status      *InverseOfferStatus_Status `protobuf:"varint,1,req,name=status,enum=allocator.InverseOfferStatus_Status" json:"status,omitempty"`
	FrameworkId *mesos.FrameworkID         `protobuf:"bytes,2,req,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	// Time, since the epoch, when this status was last updated.
	Timestamp        *mesos.TimeInfo `protobuf:"bytes,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *InverseOfferStatus) Reset()                    { *m = InverseOfferStatus{} }
func (m *InverseOfferStatus) String() string            { return proto.CompactTextString(m) }
func (*InverseOfferStatus) ProtoMessage()               {}
func (*InverseOfferStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InverseOfferStatus) GetStatus() InverseOfferStatus_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return InverseOfferStatus_UNKNOWN
}

func (m *InverseOfferStatus) GetFrameworkId() *mesos.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *InverseOfferStatus) GetTimestamp() *mesos.TimeInfo {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*InverseOfferStatus)(nil), "allocator.InverseOfferStatus")
	proto.RegisterEnum("allocator.InverseOfferStatus_Status", InverseOfferStatus_Status_name, InverseOfferStatus_Status_value)
}

func init() {
	proto.RegisterFile("github.com/miroswan/mesops/pkg/v1/allocator/allocator.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x2c, 0xca, 0x2f, 0x2e, 0x4f, 0xcc, 0xd3,
	0xcf, 0x4d, 0x2d, 0xce, 0x2f, 0x28, 0xd6, 0x2f, 0xc8, 0x4e, 0xd7, 0x2f, 0x33, 0xd4, 0x4f, 0xcc,
	0xc9, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0x2f, 0x42, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x38, 0xe1, 0x02, 0x52, 0xc6, 0x84, 0xcd, 0x01, 0xf1, 0x8a, 0x21, 0x24, 0x44, 0xbf, 0xd2, 0x0b,
	0x46, 0x2e, 0x21, 0xcf, 0xbc, 0xb2, 0xd4, 0xa2, 0xe2, 0x54, 0xff, 0xb4, 0xb4, 0xd4, 0xa2, 0xe0,
	0x92, 0xc4, 0x92, 0xd2, 0x62, 0x21, 0x1b, 0x2e, 0xb6, 0x62, 0x30, 0x4b, 0x82, 0x51, 0x81, 0x49,
	0x83, 0xcf, 0x48, 0x45, 0x0f, 0x61, 0x31, 0xa6, 0x72, 0x3d, 0x08, 0x15, 0x04, 0xd5, 0x23, 0x64,
	0xca, 0xc5, 0x93, 0x56, 0x94, 0x98, 0x9b, 0x5a, 0x9e, 0x5f, 0x94, 0x1d, 0x9f, 0x99, 0x22, 0xc1,
	0xa4, 0xc0, 0xa4, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0xb1, 0xd8, 0x0d, 0x26, 0xe5, 0xe9, 0x12, 0xc4,
	0x0d, 0x57, 0xe7, 0x99, 0x22, 0xa4, 0xcb, 0xc5, 0x59, 0x92, 0x99, 0x9b, 0x5a, 0x5c, 0x92, 0x98,
	0x5b, 0x20, 0xc1, 0x0c, 0xd6, 0xc3, 0x0f, 0xd5, 0x13, 0x92, 0x99, 0x9b, 0xea, 0x99, 0x97, 0x96,
	0x1f, 0x84, 0x50, 0xa1, 0xa4, 0xc7, 0xc5, 0x06, 0x75, 0x2d, 0x37, 0x17, 0x7b, 0xa8, 0x9f, 0xb7,
	0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0xa3, 0x10, 0x17, 0x17, 0x9b, 0xa3, 0xb3, 0xb3, 0x6b, 0x40, 0x88,
	0x00, 0x13, 0x48, 0xc2, 0xc5, 0xd5, 0xd9, 0xc7, 0xd3, 0xcf, 0x55, 0x80, 0x19, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x15, 0x1f, 0xd8, 0x68, 0x01, 0x00, 0x00,
}
