// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/miroswan/mesops/pkg/v1/maintenance/maintenance.proto

/*
Package maintenance is a generated protocol buffer package.

It is generated from these files:
	github.com/miroswan/mesops/pkg/v1/maintenance/maintenance.proto

It has these top-level messages:
	Window
	Schedule
	ClusterStatus
*/
package maintenance

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos "github.com/miroswan/mesops/pkg/v1/mesos"
import allocator "github.com/miroswan/mesops/pkg/v1/allocator"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// A set of machines scheduled to go into maintenance
// in the same `unavailability`.
type Window struct {
	// Machines affected by this maintenance window.
	MachineIds []*mesos.MachineID `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds" json:"machine_ids,omitempty"`
	// Interval during which this set of machines is expected to be down.
	Unavailability   *mesos.Unavailability `protobuf:"bytes,2,req,name=unavailability" json:"unavailability,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Window) Reset()                    { *m = Window{} }
func (m *Window) String() string            { return proto.CompactTextString(m) }
func (*Window) ProtoMessage()               {}
func (*Window) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Window) GetMachineIds() []*mesos.MachineID {
	if m != nil {
		return m.MachineIds
	}
	return nil
}

func (m *Window) GetUnavailability() *mesos.Unavailability {
	if m != nil {
		return m.Unavailability
	}
	return nil
}

// *
// A list of maintenance windows.
// For example, this may represent a rolling restart of agents.
type Schedule struct {
	Windows          []*Window `protobuf:"bytes,1,rep,name=windows" json:"windows,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Schedule) GetWindows() []*Window {
	if m != nil {
		return m.Windows
	}
	return nil
}

// *
// Represents the maintenance status of each machine in the cluster.
// The lists correspond to the `MachineInfo.Mode` enumeration.
type ClusterStatus struct {
	DrainingMachines []*ClusterStatus_DrainingMachine `protobuf:"bytes,1,rep,name=draining_machines,json=drainingMachines" json:"draining_machines,omitempty"`
	DownMachines     []*mesos.MachineID               `protobuf:"bytes,2,rep,name=down_machines,json=downMachines" json:"down_machines,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ClusterStatus) Reset()                    { *m = ClusterStatus{} }
func (m *ClusterStatus) String() string            { return proto.CompactTextString(m) }
func (*ClusterStatus) ProtoMessage()               {}
func (*ClusterStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClusterStatus) GetDrainingMachines() []*ClusterStatus_DrainingMachine {
	if m != nil {
		return m.DrainingMachines
	}
	return nil
}

func (m *ClusterStatus) GetDownMachines() []*mesos.MachineID {
	if m != nil {
		return m.DownMachines
	}
	return nil
}

type ClusterStatus_DrainingMachine struct {
	Id *mesos.MachineID `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// A list of the most recent responses to inverse offers from frameworks
	// running on this draining machine.
	Statuses         []*allocator.InverseOfferStatus `protobuf:"bytes,2,rep,name=statuses" json:"statuses,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ClusterStatus_DrainingMachine) Reset()         { *m = ClusterStatus_DrainingMachine{} }
func (m *ClusterStatus_DrainingMachine) String() string { return proto.CompactTextString(m) }
func (*ClusterStatus_DrainingMachine) ProtoMessage()    {}
func (*ClusterStatus_DrainingMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *ClusterStatus_DrainingMachine) GetId() *mesos.MachineID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ClusterStatus_DrainingMachine) GetStatuses() []*allocator.InverseOfferStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func init() {
	proto.RegisterType((*Window)(nil), "maintenance.Window")
	proto.RegisterType((*Schedule)(nil), "maintenance.Schedule")
	proto.RegisterType((*ClusterStatus)(nil), "maintenance.ClusterStatus")
	proto.RegisterType((*ClusterStatus_DrainingMachine)(nil), "maintenance.ClusterStatus.DrainingMachine")
}

func init() {
	proto.RegisterFile("github.com/miroswan/mesops/pkg/v1/maintenance/maintenance.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xd1, 0x4b, 0xeb, 0x30,
	0x14, 0xc6, 0x59, 0x2f, 0xec, 0x8e, 0xd3, 0xbb, 0xeb, 0x8c, 0x08, 0x63, 0x28, 0x8c, 0x3d, 0xc8,
	0x10, 0x4c, 0xd9, 0xc4, 0x87, 0x21, 0x22, 0xcc, 0xbd, 0xec, 0x41, 0x94, 0x0e, 0xd9, 0xe3, 0xc8,
	0x9a, 0xac, 0x0d, 0xb6, 0x49, 0x49, 0xd2, 0x15, 0xfd, 0x27, 0xfc, 0x97, 0x65, 0x6b, 0xbb, 0xb5,
	0x13, 0xd1, 0x97, 0x10, 0x92, 0xef, 0xfb, 0x9d, 0xef, 0x9c, 0x03, 0xf7, 0x3e, 0x37, 0x41, 0xb2,
	0xc4, 0x9e, 0x8c, 0x9c, 0x88, 0x2b, 0xa9, 0x53, 0x22, 0x9c, 0x88, 0x69, 0x19, 0x6b, 0x27, 0x7e,
	0xf5, 0x9d, 0xf5, 0xc0, 0x89, 0x08, 0x17, 0x86, 0x09, 0x22, 0x3c, 0x56, 0xbe, 0xe3, 0x58, 0x49,
	0x23, 0x91, 0x5d, 0x7a, 0xea, 0x5c, 0xff, 0x82, 0xc6, 0xb4, 0xd4, 0xd9, 0x99, 0x11, 0x3a, 0xb7,
	0x3f, 0x9b, 0x48, 0x18, 0x4a, 0x8f, 0x18, 0xa9, 0xf6, 0xb7, 0xcc, 0xdc, 0x7b, 0x87, 0xfa, 0x9c,
	0x0b, 0x2a, 0x53, 0x34, 0x00, 0x3b, 0x22, 0x5e, 0xc0, 0x05, 0x5b, 0x70, 0xaa, 0xdb, 0xb5, 0xee,
	0x9f, 0xbe, 0x3d, 0x6c, 0xe1, 0xac, 0xd2, 0x63, 0xf6, 0x33, 0x9d, 0xb8, 0x90, 0x8b, 0xa6, 0x54,
	0xa3, 0x3b, 0xf8, 0x9f, 0x08, 0xb2, 0x26, 0x3c, 0x24, 0x4b, 0x1e, 0x72, 0xf3, 0xd6, 0xb6, 0xba,
	0x56, 0xdf, 0x1e, 0x9e, 0xe6, 0xae, 0x97, 0xca, 0xa7, 0x7b, 0x20, 0xee, 0x8d, 0xa0, 0x31, 0xf3,
	0x02, 0x46, 0x93, 0x90, 0xa1, 0x2b, 0xf8, 0x9b, 0x6e, 0x73, 0x14, 0x95, 0x4f, 0x70, 0x79, 0x56,
	0x59, 0x46, 0xb7, 0xd0, 0xf4, 0x3e, 0x2c, 0x68, 0x3e, 0x84, 0x89, 0x36, 0x4c, 0xcd, 0x0c, 0x31,
	0x89, 0x46, 0x73, 0x38, 0xa6, 0x8a, 0x70, 0xc1, 0x85, 0xbf, 0xc8, 0x23, 0x16, 0xa8, 0xcb, 0x0a,
	0xaa, 0x62, 0xc3, 0x93, 0xdc, 0x93, 0x37, 0xe8, 0xb6, 0x68, 0xf5, 0x41, 0xa3, 0x1b, 0x68, 0x52,
	0x99, 0x8a, 0x3d, 0xd4, 0xfa, 0x66, 0x32, 0xff, 0x36, 0xb2, 0xc2, 0xd6, 0x11, 0x70, 0x74, 0xc0,
	0x46, 0x5d, 0xb0, 0x38, 0x6d, 0xd7, 0xb6, 0x23, 0xfa, 0x6a, 0xb7, 0x38, 0x45, 0x23, 0x68, 0xe8,
	0x6d, 0xae, 0x5d, 0x99, 0x73, 0xbc, 0xdf, 0xd8, 0x54, 0xac, 0x99, 0xd2, 0xec, 0x69, 0xb5, 0x2a,
	0xe2, 0xbb, 0x3b, 0xf9, 0xf8, 0x02, 0xce, 0xa4, 0xf2, 0x31, 0x89, 0x89, 0x17, 0xb0, 0x1c, 0x5e,
	0x6a, 0x7b, 0x5c, 0x7f, 0xde, 0xec, 0x5b, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x32, 0xdf,
	0xd5, 0xb1, 0x02, 0x00, 0x00,
}
