// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/miroswan/mesops/pkg/v1/agent/agent.proto

/*
Package agent is a generated protocol buffer package.

It is generated from these files:
	github.com/miroswan/mesops/pkg/v1/agent/agent.proto

It has these top-level messages:
	Call
	Response
	ProcessIO
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos "github.com/miroswan/mesops/pkg/v1/mesos"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// If a call of type `Call::FOO` requires additional parameters they can be
// included in the corresponding `Call::Foo` message. Similarly, if a call
// receives a synchronous response it will be returned as a `Response`
// message of type `Response::FOO`; see `Call::LaunchNestedContainerSession`
// and `Call::AttachContainerOutput` for exceptions.
type Call_Type int32

const (
	Call_UNKNOWN           Call_Type = 0
	Call_GET_HEALTH        Call_Type = 1
	Call_GET_FLAGS         Call_Type = 2
	Call_GET_VERSION       Call_Type = 3
	Call_GET_METRICS       Call_Type = 4
	Call_GET_LOGGING_LEVEL Call_Type = 5
	Call_SET_LOGGING_LEVEL Call_Type = 6
	Call_LIST_FILES        Call_Type = 7
	Call_READ_FILE         Call_Type = 8
	Call_GET_STATE         Call_Type = 9
	Call_GET_CONTAINERS    Call_Type = 10
	Call_GET_FRAMEWORKS    Call_Type = 11
	Call_GET_EXECUTORS     Call_Type = 12
	Call_GET_TASKS         Call_Type = 13
	Call_GET_AGENT         Call_Type = 20
	// Calls for managing nested containers underneath an executor's container.
	Call_LAUNCH_NESTED_CONTAINER Call_Type = 14
	Call_WAIT_NESTED_CONTAINER   Call_Type = 15
	Call_KILL_NESTED_CONTAINER   Call_Type = 16
	Call_REMOVE_NESTED_CONTAINER Call_Type = 21
	// See 'LaunchNestedContainerSession' below.
	Call_LAUNCH_NESTED_CONTAINER_SESSION Call_Type = 17
	Call_ATTACH_CONTAINER_INPUT          Call_Type = 18
	Call_ATTACH_CONTAINER_OUTPUT         Call_Type = 19
)

var Call_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GET_HEALTH",
	2:  "GET_FLAGS",
	3:  "GET_VERSION",
	4:  "GET_METRICS",
	5:  "GET_LOGGING_LEVEL",
	6:  "SET_LOGGING_LEVEL",
	7:  "LIST_FILES",
	8:  "READ_FILE",
	9:  "GET_STATE",
	10: "GET_CONTAINERS",
	11: "GET_FRAMEWORKS",
	12: "GET_EXECUTORS",
	13: "GET_TASKS",
	20: "GET_AGENT",
	14: "LAUNCH_NESTED_CONTAINER",
	15: "WAIT_NESTED_CONTAINER",
	16: "KILL_NESTED_CONTAINER",
	21: "REMOVE_NESTED_CONTAINER",
	17: "LAUNCH_NESTED_CONTAINER_SESSION",
	18: "ATTACH_CONTAINER_INPUT",
	19: "ATTACH_CONTAINER_OUTPUT",
}
var Call_Type_value = map[string]int32{
	"UNKNOWN":                         0,
	"GET_HEALTH":                      1,
	"GET_FLAGS":                       2,
	"GET_VERSION":                     3,
	"GET_METRICS":                     4,
	"GET_LOGGING_LEVEL":               5,
	"SET_LOGGING_LEVEL":               6,
	"LIST_FILES":                      7,
	"READ_FILE":                       8,
	"GET_STATE":                       9,
	"GET_CONTAINERS":                  10,
	"GET_FRAMEWORKS":                  11,
	"GET_EXECUTORS":                   12,
	"GET_TASKS":                       13,
	"GET_AGENT":                       20,
	"LAUNCH_NESTED_CONTAINER":         14,
	"WAIT_NESTED_CONTAINER":           15,
	"KILL_NESTED_CONTAINER":           16,
	"REMOVE_NESTED_CONTAINER":         21,
	"LAUNCH_NESTED_CONTAINER_SESSION": 17,
	"ATTACH_CONTAINER_INPUT":          18,
	"ATTACH_CONTAINER_OUTPUT":         19,
}

func (x Call_Type) Enum() *Call_Type {
	p := new(Call_Type)
	*p = x
	return p
}
func (x Call_Type) String() string {
	return proto.EnumName(Call_Type_name, int32(x))
}
func (x *Call_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Call_Type_value, data, "Call_Type")
	if err != nil {
		return err
	}
	*x = Call_Type(value)
	return nil
}
func (Call_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Call_AttachContainerInput_Type int32

const (
	Call_AttachContainerInput_UNKNOWN      Call_AttachContainerInput_Type = 0
	Call_AttachContainerInput_CONTAINER_ID Call_AttachContainerInput_Type = 1
	Call_AttachContainerInput_PROCESS_IO   Call_AttachContainerInput_Type = 2
)

var Call_AttachContainerInput_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CONTAINER_ID",
	2: "PROCESS_IO",
}
var Call_AttachContainerInput_Type_value = map[string]int32{
	"UNKNOWN":      0,
	"CONTAINER_ID": 1,
	"PROCESS_IO":   2,
}

func (x Call_AttachContainerInput_Type) Enum() *Call_AttachContainerInput_Type {
	p := new(Call_AttachContainerInput_Type)
	*p = x
	return p
}
func (x Call_AttachContainerInput_Type) String() string {
	return proto.EnumName(Call_AttachContainerInput_Type_name, int32(x))
}
func (x *Call_AttachContainerInput_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Call_AttachContainerInput_Type_value, data, "Call_AttachContainerInput_Type")
	if err != nil {
		return err
	}
	*x = Call_AttachContainerInput_Type(value)
	return nil
}
func (Call_AttachContainerInput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 9, 0}
}

// Each of the responses of type `FOO` corresponds to `Foo` message below.
type Response_Type int32

const (
	Response_UNKNOWN               Response_Type = 0
	Response_GET_HEALTH            Response_Type = 1
	Response_GET_FLAGS             Response_Type = 2
	Response_GET_VERSION           Response_Type = 3
	Response_GET_METRICS           Response_Type = 4
	Response_GET_LOGGING_LEVEL     Response_Type = 5
	Response_LIST_FILES            Response_Type = 6
	Response_READ_FILE             Response_Type = 7
	Response_GET_STATE             Response_Type = 8
	Response_GET_CONTAINERS        Response_Type = 9
	Response_GET_FRAMEWORKS        Response_Type = 10
	Response_GET_EXECUTORS         Response_Type = 11
	Response_GET_TASKS             Response_Type = 12
	Response_GET_AGENT             Response_Type = 14
	Response_WAIT_NESTED_CONTAINER Response_Type = 13
)

var Response_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GET_HEALTH",
	2:  "GET_FLAGS",
	3:  "GET_VERSION",
	4:  "GET_METRICS",
	5:  "GET_LOGGING_LEVEL",
	6:  "LIST_FILES",
	7:  "READ_FILE",
	8:  "GET_STATE",
	9:  "GET_CONTAINERS",
	10: "GET_FRAMEWORKS",
	11: "GET_EXECUTORS",
	12: "GET_TASKS",
	14: "GET_AGENT",
	13: "WAIT_NESTED_CONTAINER",
}
var Response_Type_value = map[string]int32{
	"UNKNOWN":               0,
	"GET_HEALTH":            1,
	"GET_FLAGS":             2,
	"GET_VERSION":           3,
	"GET_METRICS":           4,
	"GET_LOGGING_LEVEL":     5,
	"LIST_FILES":            6,
	"READ_FILE":             7,
	"GET_STATE":             8,
	"GET_CONTAINERS":        9,
	"GET_FRAMEWORKS":        10,
	"GET_EXECUTORS":         11,
	"GET_TASKS":             12,
	"GET_AGENT":             14,
	"WAIT_NESTED_CONTAINER": 13,
}

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}
func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (x *Response_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Type_value, data, "Response_Type")
	if err != nil {
		return err
	}
	*x = Response_Type(value)
	return nil
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ProcessIO_Type int32

const (
	ProcessIO_UNKNOWN ProcessIO_Type = 0
	ProcessIO_DATA    ProcessIO_Type = 1
	ProcessIO_CONTROL ProcessIO_Type = 2
)

var ProcessIO_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "DATA",
	2: "CONTROL",
}
var ProcessIO_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"DATA":    1,
	"CONTROL": 2,
}

func (x ProcessIO_Type) Enum() *ProcessIO_Type {
	p := new(ProcessIO_Type)
	*p = x
	return p
}
func (x ProcessIO_Type) String() string {
	return proto.EnumName(ProcessIO_Type_name, int32(x))
}
func (x *ProcessIO_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProcessIO_Type_value, data, "ProcessIO_Type")
	if err != nil {
		return err
	}
	*x = ProcessIO_Type(value)
	return nil
}
func (ProcessIO_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ProcessIO_Data_Type int32

const (
	ProcessIO_Data_UNKNOWN ProcessIO_Data_Type = 0
	ProcessIO_Data_STDIN   ProcessIO_Data_Type = 1
	ProcessIO_Data_STDOUT  ProcessIO_Data_Type = 2
	ProcessIO_Data_STDERR  ProcessIO_Data_Type = 3
)

var ProcessIO_Data_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "STDIN",
	2: "STDOUT",
	3: "STDERR",
}
var ProcessIO_Data_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"STDIN":   1,
	"STDOUT":  2,
	"STDERR":  3,
}

func (x ProcessIO_Data_Type) Enum() *ProcessIO_Data_Type {
	p := new(ProcessIO_Data_Type)
	*p = x
	return p
}
func (x ProcessIO_Data_Type) String() string {
	return proto.EnumName(ProcessIO_Data_Type_name, int32(x))
}
func (x *ProcessIO_Data_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProcessIO_Data_Type_value, data, "ProcessIO_Data_Type")
	if err != nil {
		return err
	}
	*x = ProcessIO_Data_Type(value)
	return nil
}
func (ProcessIO_Data_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0, 0} }

type ProcessIO_Control_Type int32

const (
	ProcessIO_Control_UNKNOWN   ProcessIO_Control_Type = 0
	ProcessIO_Control_TTY_INFO  ProcessIO_Control_Type = 1
	ProcessIO_Control_HEARTBEAT ProcessIO_Control_Type = 2
)

var ProcessIO_Control_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "TTY_INFO",
	2: "HEARTBEAT",
}
var ProcessIO_Control_Type_value = map[string]int32{
	"UNKNOWN":   0,
	"TTY_INFO":  1,
	"HEARTBEAT": 2,
}

func (x ProcessIO_Control_Type) Enum() *ProcessIO_Control_Type {
	p := new(ProcessIO_Control_Type)
	*p = x
	return p
}
func (x ProcessIO_Control_Type) String() string {
	return proto.EnumName(ProcessIO_Control_Type_name, int32(x))
}
func (x *ProcessIO_Control_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProcessIO_Control_Type_value, data, "ProcessIO_Control_Type")
	if err != nil {
		return err
	}
	*x = ProcessIO_Control_Type(value)
	return nil
}
func (ProcessIO_Control_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1, 0} }

// *
// Calls that can be sent to the agent API.
//
// A call is described using the standard protocol buffer "union"
// trick, see
// https://developers.google.com/protocol-buffers/docs/techniques#union.
type Call struct {
	Type                         *Call_Type                         `protobuf:"varint,1,opt,name=type,enum=agent.Call_Type" json:"type,omitempty"`
	GetMetrics                   *Call_GetMetrics                   `protobuf:"bytes,2,opt,name=get_metrics,json=getMetrics" json:"get_metrics,omitempty"`
	SetLoggingLevel              *Call_SetLoggingLevel              `protobuf:"bytes,3,opt,name=set_logging_level,json=setLoggingLevel" json:"set_logging_level,omitempty"`
	ListFiles                    *Call_ListFiles                    `protobuf:"bytes,4,opt,name=list_files,json=listFiles" json:"list_files,omitempty"`
	ReadFile                     *Call_ReadFile                     `protobuf:"bytes,5,opt,name=read_file,json=readFile" json:"read_file,omitempty"`
	LaunchNestedContainer        *Call_LaunchNestedContainer        `protobuf:"bytes,6,opt,name=launch_nested_container,json=launchNestedContainer" json:"launch_nested_container,omitempty"`
	WaitNestedContainer          *Call_WaitNestedContainer          `protobuf:"bytes,7,opt,name=wait_nested_container,json=waitNestedContainer" json:"wait_nested_container,omitempty"`
	KillNestedContainer          *Call_KillNestedContainer          `protobuf:"bytes,8,opt,name=kill_nested_container,json=killNestedContainer" json:"kill_nested_container,omitempty"`
	RemoveNestedContainer        *Call_RemoveNestedContainer        `protobuf:"bytes,12,opt,name=remove_nested_container,json=removeNestedContainer" json:"remove_nested_container,omitempty"`
	LaunchNestedContainerSession *Call_LaunchNestedContainerSession `protobuf:"bytes,9,opt,name=launch_nested_container_session,json=launchNestedContainerSession" json:"launch_nested_container_session,omitempty"`
	AttachContainerInput         *Call_AttachContainerInput         `protobuf:"bytes,10,opt,name=attach_container_input,json=attachContainerInput" json:"attach_container_input,omitempty"`
	AttachContainerOutput        *Call_AttachContainerOutput        `protobuf:"bytes,11,opt,name=attach_container_output,json=attachContainerOutput" json:"attach_container_output,omitempty"`
	XXX_unrecognized             []byte                             `json:"-"`
}

func (m *Call) Reset()                    { *m = Call{} }
func (m *Call) String() string            { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()               {}
func (*Call) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Call) GetType() Call_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Call_UNKNOWN
}

func (m *Call) GetGetMetrics() *Call_GetMetrics {
	if m != nil {
		return m.GetMetrics
	}
	return nil
}

func (m *Call) GetSetLoggingLevel() *Call_SetLoggingLevel {
	if m != nil {
		return m.SetLoggingLevel
	}
	return nil
}

func (m *Call) GetListFiles() *Call_ListFiles {
	if m != nil {
		return m.ListFiles
	}
	return nil
}

func (m *Call) GetReadFile() *Call_ReadFile {
	if m != nil {
		return m.ReadFile
	}
	return nil
}

func (m *Call) GetLaunchNestedContainer() *Call_LaunchNestedContainer {
	if m != nil {
		return m.LaunchNestedContainer
	}
	return nil
}

func (m *Call) GetWaitNestedContainer() *Call_WaitNestedContainer {
	if m != nil {
		return m.WaitNestedContainer
	}
	return nil
}

func (m *Call) GetKillNestedContainer() *Call_KillNestedContainer {
	if m != nil {
		return m.KillNestedContainer
	}
	return nil
}

func (m *Call) GetRemoveNestedContainer() *Call_RemoveNestedContainer {
	if m != nil {
		return m.RemoveNestedContainer
	}
	return nil
}

func (m *Call) GetLaunchNestedContainerSession() *Call_LaunchNestedContainerSession {
	if m != nil {
		return m.LaunchNestedContainerSession
	}
	return nil
}

func (m *Call) GetAttachContainerInput() *Call_AttachContainerInput {
	if m != nil {
		return m.AttachContainerInput
	}
	return nil
}

func (m *Call) GetAttachContainerOutput() *Call_AttachContainerOutput {
	if m != nil {
		return m.AttachContainerOutput
	}
	return nil
}

// Provides a snapshot of the current metrics tracked by the agent.
type Call_GetMetrics struct {
	// If set, `timeout` would be used to determines the maximum amount of time
	// the API will take to respond. If the timeout is exceeded, some metrics
	// may not be included in the response.
	Timeout          *mesos.DurationInfo `protobuf:"bytes,1,opt,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_GetMetrics) Reset()                    { *m = Call_GetMetrics{} }
func (m *Call_GetMetrics) String() string            { return proto.CompactTextString(m) }
func (*Call_GetMetrics) ProtoMessage()               {}
func (*Call_GetMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Call_GetMetrics) GetTimeout() *mesos.DurationInfo {
	if m != nil {
		return m.Timeout
	}
	return nil
}

// Sets the logging verbosity level for a specified duration. Mesos uses
// [glog](https://github.com/google/glog) for logging. The library only uses
// verbose logging which means nothing will be output unless the verbosity
// level is set (by default it's 0, libprocess uses levels 1, 2, and 3).
type Call_SetLoggingLevel struct {
	// The verbosity level.
	Level *uint32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	// The duration to keep verbosity level toggled. After this duration, the
	// verbosity level of log would revert to the original level.
	Duration         *mesos.DurationInfo `protobuf:"bytes,2,req,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_SetLoggingLevel) Reset()                    { *m = Call_SetLoggingLevel{} }
func (m *Call_SetLoggingLevel) String() string            { return proto.CompactTextString(m) }
func (*Call_SetLoggingLevel) ProtoMessage()               {}
func (*Call_SetLoggingLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Call_SetLoggingLevel) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Call_SetLoggingLevel) GetDuration() *mesos.DurationInfo {
	if m != nil {
		return m.Duration
	}
	return nil
}

// Provides the file listing for a directory.
type Call_ListFiles struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Call_ListFiles) Reset()                    { *m = Call_ListFiles{} }
func (m *Call_ListFiles) String() string            { return proto.CompactTextString(m) }
func (*Call_ListFiles) ProtoMessage()               {}
func (*Call_ListFiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Call_ListFiles) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

// Reads data from a file.
type Call_ReadFile struct {
	// The path of file.
	Path *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	// Initial offset in file to start reading from.
	Offset *uint64 `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	// The maximum number of bytes to read. The read length is capped at 16
	// memory pages.
	Length           *uint64 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Call_ReadFile) Reset()                    { *m = Call_ReadFile{} }
func (m *Call_ReadFile) String() string            { return proto.CompactTextString(m) }
func (*Call_ReadFile) ProtoMessage()               {}
func (*Call_ReadFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Call_ReadFile) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Call_ReadFile) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *Call_ReadFile) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

// Launches a nested container within an executor's tree of containers.
type Call_LaunchNestedContainer struct {
	ContainerId      *mesos.ContainerID   `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	Command          *mesos.CommandInfo   `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Container        *mesos.ContainerInfo `protobuf:"bytes,3,opt,name=container" json:"container,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Call_LaunchNestedContainer) Reset()                    { *m = Call_LaunchNestedContainer{} }
func (m *Call_LaunchNestedContainer) String() string            { return proto.CompactTextString(m) }
func (*Call_LaunchNestedContainer) ProtoMessage()               {}
func (*Call_LaunchNestedContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Call_LaunchNestedContainer) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *Call_LaunchNestedContainer) GetCommand() *mesos.CommandInfo {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Call_LaunchNestedContainer) GetContainer() *mesos.ContainerInfo {
	if m != nil {
		return m.Container
	}
	return nil
}

// Waits for the nested container to terminate and receives the exit status.
type Call_WaitNestedContainer struct {
	ContainerId      *mesos.ContainerID `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_WaitNestedContainer) Reset()                    { *m = Call_WaitNestedContainer{} }
func (m *Call_WaitNestedContainer) String() string            { return proto.CompactTextString(m) }
func (*Call_WaitNestedContainer) ProtoMessage()               {}
func (*Call_WaitNestedContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Call_WaitNestedContainer) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

// Kills the nested container. The signal (e.g., SIGTERM, SIGKILL, etc.)
// to be sent to the container can be specified in the 'signal' field.
// If 'signal' is not set, SIGKILL is used by default.
type Call_KillNestedContainer struct {
	ContainerId      *mesos.ContainerID `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	Signal           *int32             `protobuf:"varint,2,opt,name=signal" json:"signal,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_KillNestedContainer) Reset()                    { *m = Call_KillNestedContainer{} }
func (m *Call_KillNestedContainer) String() string            { return proto.CompactTextString(m) }
func (*Call_KillNestedContainer) ProtoMessage()               {}
func (*Call_KillNestedContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *Call_KillNestedContainer) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *Call_KillNestedContainer) GetSignal() int32 {
	if m != nil && m.Signal != nil {
		return *m.Signal
	}
	return 0
}

// Removes a nested container and its artifacts (runtime and sandbox
// directories).
type Call_RemoveNestedContainer struct {
	ContainerId      *mesos.ContainerID `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_RemoveNestedContainer) Reset()                    { *m = Call_RemoveNestedContainer{} }
func (m *Call_RemoveNestedContainer) String() string            { return proto.CompactTextString(m) }
func (*Call_RemoveNestedContainer) ProtoMessage()               {}
func (*Call_RemoveNestedContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 7} }

func (m *Call_RemoveNestedContainer) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

// Launches a nested container within an executor's tree of containers.
// The differences between this call and `LaunchNestedContainer` are:
// 1) The container's life-cycle is tied to the lifetime of the
//    connection used to make this call, i.e., if the connection ever
//    breaks, the container will be destroyed.
// 2) The nested container shares the same namespaces and cgroups as
//    its parent container.
// 3) Results in a streaming response of type `ProcessIO`. So the call
//    needs to be made on a persistent connection.
type Call_LaunchNestedContainerSession struct {
	ContainerId      *mesos.ContainerID   `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	Command          *mesos.CommandInfo   `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Container        *mesos.ContainerInfo `protobuf:"bytes,3,opt,name=container" json:"container,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Call_LaunchNestedContainerSession) Reset()         { *m = Call_LaunchNestedContainerSession{} }
func (m *Call_LaunchNestedContainerSession) String() string { return proto.CompactTextString(m) }
func (*Call_LaunchNestedContainerSession) ProtoMessage()    {}
func (*Call_LaunchNestedContainerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 8}
}

func (m *Call_LaunchNestedContainerSession) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *Call_LaunchNestedContainerSession) GetCommand() *mesos.CommandInfo {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Call_LaunchNestedContainerSession) GetContainer() *mesos.ContainerInfo {
	if m != nil {
		return m.Container
	}
	return nil
}

// Attaches the caller to the STDIN of the entry point of the container.
// Clients can use this to stream input data to a container.
// Note that this call needs to be made on a persistent connection by
// streaming a CONTAINER_ID message followed by one or more PROCESS_IO
// messages.
type Call_AttachContainerInput struct {
	Type             *Call_AttachContainerInput_Type `protobuf:"varint,1,opt,name=type,enum=agent.Call_AttachContainerInput_Type" json:"type,omitempty"`
	ContainerId      *mesos.ContainerID              `protobuf:"bytes,2,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ProcessIo        *ProcessIO                      `protobuf:"bytes,3,opt,name=process_io,json=processIo" json:"process_io,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *Call_AttachContainerInput) Reset()                    { *m = Call_AttachContainerInput{} }
func (m *Call_AttachContainerInput) String() string            { return proto.CompactTextString(m) }
func (*Call_AttachContainerInput) ProtoMessage()               {}
func (*Call_AttachContainerInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 9} }

func (m *Call_AttachContainerInput) GetType() Call_AttachContainerInput_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Call_AttachContainerInput_UNKNOWN
}

func (m *Call_AttachContainerInput) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *Call_AttachContainerInput) GetProcessIo() *ProcessIO {
	if m != nil {
		return m.ProcessIo
	}
	return nil
}

// Attaches the caller to the STDOUT and STDERR of the entrypoint of
// the container. Clients can use this to stream output/error from the
// container. This call will result in a streaming response of `ProcessIO`;
// so this call needs to be made on a persistent connection.
type Call_AttachContainerOutput struct {
	ContainerId      *mesos.ContainerID `protobuf:"bytes,1,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_AttachContainerOutput) Reset()                    { *m = Call_AttachContainerOutput{} }
func (m *Call_AttachContainerOutput) String() string            { return proto.CompactTextString(m) }
func (*Call_AttachContainerOutput) ProtoMessage()               {}
func (*Call_AttachContainerOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 10} }

func (m *Call_AttachContainerOutput) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

// *
// Synchronous responses for all calls made to the agent API.
type Response struct {
	Type                *Response_Type                `protobuf:"varint,1,opt,name=type,enum=agent.Response_Type" json:"type,omitempty"`
	GetHealth           *Response_GetHealth           `protobuf:"bytes,2,opt,name=get_health,json=getHealth" json:"get_health,omitempty"`
	GetFlags            *Response_GetFlags            `protobuf:"bytes,3,opt,name=get_flags,json=getFlags" json:"get_flags,omitempty"`
	GetVersion          *Response_GetVersion          `protobuf:"bytes,4,opt,name=get_version,json=getVersion" json:"get_version,omitempty"`
	GetMetrics          *Response_GetMetrics          `protobuf:"bytes,5,opt,name=get_metrics,json=getMetrics" json:"get_metrics,omitempty"`
	GetLoggingLevel     *Response_GetLoggingLevel     `protobuf:"bytes,6,opt,name=get_logging_level,json=getLoggingLevel" json:"get_logging_level,omitempty"`
	ListFiles           *Response_ListFiles           `protobuf:"bytes,7,opt,name=list_files,json=listFiles" json:"list_files,omitempty"`
	ReadFile            *Response_ReadFile            `protobuf:"bytes,8,opt,name=read_file,json=readFile" json:"read_file,omitempty"`
	GetState            *Response_GetState            `protobuf:"bytes,9,opt,name=get_state,json=getState" json:"get_state,omitempty"`
	GetContainers       *Response_GetContainers       `protobuf:"bytes,10,opt,name=get_containers,json=getContainers" json:"get_containers,omitempty"`
	GetFrameworks       *Response_GetFrameworks       `protobuf:"bytes,11,opt,name=get_frameworks,json=getFrameworks" json:"get_frameworks,omitempty"`
	GetExecutors        *Response_GetExecutors        `protobuf:"bytes,12,opt,name=get_executors,json=getExecutors" json:"get_executors,omitempty"`
	GetTasks            *Response_GetTasks            `protobuf:"bytes,13,opt,name=get_tasks,json=getTasks" json:"get_tasks,omitempty"`
	GetAgent            *Response_GetAgent            `protobuf:"bytes,15,opt,name=get_agent,json=getAgent" json:"get_agent,omitempty"`
	WaitNestedContainer *Response_WaitNestedContainer `protobuf:"bytes,14,opt,name=wait_nested_container,json=waitNestedContainer" json:"wait_nested_container,omitempty"`
	XXX_unrecognized    []byte                        `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetType() Response_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Response_UNKNOWN
}

func (m *Response) GetGetHealth() *Response_GetHealth {
	if m != nil {
		return m.GetHealth
	}
	return nil
}

func (m *Response) GetGetFlags() *Response_GetFlags {
	if m != nil {
		return m.GetFlags
	}
	return nil
}

func (m *Response) GetGetVersion() *Response_GetVersion {
	if m != nil {
		return m.GetVersion
	}
	return nil
}

func (m *Response) GetGetMetrics() *Response_GetMetrics {
	if m != nil {
		return m.GetMetrics
	}
	return nil
}

func (m *Response) GetGetLoggingLevel() *Response_GetLoggingLevel {
	if m != nil {
		return m.GetLoggingLevel
	}
	return nil
}

func (m *Response) GetListFiles() *Response_ListFiles {
	if m != nil {
		return m.ListFiles
	}
	return nil
}

func (m *Response) GetReadFile() *Response_ReadFile {
	if m != nil {
		return m.ReadFile
	}
	return nil
}

func (m *Response) GetGetState() *Response_GetState {
	if m != nil {
		return m.GetState
	}
	return nil
}

func (m *Response) GetGetContainers() *Response_GetContainers {
	if m != nil {
		return m.GetContainers
	}
	return nil
}

func (m *Response) GetGetFrameworks() *Response_GetFrameworks {
	if m != nil {
		return m.GetFrameworks
	}
	return nil
}

func (m *Response) GetGetExecutors() *Response_GetExecutors {
	if m != nil {
		return m.GetExecutors
	}
	return nil
}

func (m *Response) GetGetTasks() *Response_GetTasks {
	if m != nil {
		return m.GetTasks
	}
	return nil
}

func (m *Response) GetGetAgent() *Response_GetAgent {
	if m != nil {
		return m.GetAgent
	}
	return nil
}

func (m *Response) GetWaitNestedContainer() *Response_WaitNestedContainer {
	if m != nil {
		return m.WaitNestedContainer
	}
	return nil
}

// `healthy` would be true if the agent is healthy. Delayed responses are also
// indicative of the poor health of the agent.
type Response_GetHealth struct {
	Healthy          *bool  `protobuf:"varint,1,req,name=healthy" json:"healthy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response_GetHealth) Reset()                    { *m = Response_GetHealth{} }
func (m *Response_GetHealth) String() string            { return proto.CompactTextString(m) }
func (*Response_GetHealth) ProtoMessage()               {}
func (*Response_GetHealth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_GetHealth) GetHealthy() bool {
	if m != nil && m.Healthy != nil {
		return *m.Healthy
	}
	return false
}

// Contains the flag configuration of the agent.
type Response_GetFlags struct {
	Flags            []*mesos.Flag `protobuf:"bytes,1,rep,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Response_GetFlags) Reset()                    { *m = Response_GetFlags{} }
func (m *Response_GetFlags) String() string            { return proto.CompactTextString(m) }
func (*Response_GetFlags) ProtoMessage()               {}
func (*Response_GetFlags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *Response_GetFlags) GetFlags() []*mesos.Flag {
	if m != nil {
		return m.Flags
	}
	return nil
}

// Contains the version information of the agent.
type Response_GetVersion struct {
	VersionInfo      *mesos.VersionInfo `protobuf:"bytes,1,req,name=version_info,json=versionInfo" json:"version_info,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Response_GetVersion) Reset()                    { *m = Response_GetVersion{} }
func (m *Response_GetVersion) String() string            { return proto.CompactTextString(m) }
func (*Response_GetVersion) ProtoMessage()               {}
func (*Response_GetVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *Response_GetVersion) GetVersionInfo() *mesos.VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

// Contains a snapshot of the current metrics.
type Response_GetMetrics struct {
	Metrics          []*mesos.Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response_GetMetrics) Reset()                    { *m = Response_GetMetrics{} }
func (m *Response_GetMetrics) String() string            { return proto.CompactTextString(m) }
func (*Response_GetMetrics) ProtoMessage()               {}
func (*Response_GetMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 3} }

func (m *Response_GetMetrics) GetMetrics() []*mesos.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Contains the logging level of the agent.
type Response_GetLoggingLevel struct {
	Level            *uint32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response_GetLoggingLevel) Reset()                    { *m = Response_GetLoggingLevel{} }
func (m *Response_GetLoggingLevel) String() string            { return proto.CompactTextString(m) }
func (*Response_GetLoggingLevel) ProtoMessage()               {}
func (*Response_GetLoggingLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

func (m *Response_GetLoggingLevel) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

// Contains the file listing(similar to `ls -l`) for a directory.
type Response_ListFiles struct {
	FileInfos        []*mesos.FileInfo `protobuf:"bytes,1,rep,name=file_infos,json=fileInfos" json:"file_infos,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Response_ListFiles) Reset()                    { *m = Response_ListFiles{} }
func (m *Response_ListFiles) String() string            { return proto.CompactTextString(m) }
func (*Response_ListFiles) ProtoMessage()               {}
func (*Response_ListFiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

func (m *Response_ListFiles) GetFileInfos() []*mesos.FileInfo {
	if m != nil {
		return m.FileInfos
	}
	return nil
}

// Contains the file data.
type Response_ReadFile struct {
	// The size of file (in bytes).
	Size             *uint64 `protobuf:"varint,1,req,name=size" json:"size,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response_ReadFile) Reset()                    { *m = Response_ReadFile{} }
func (m *Response_ReadFile) String() string            { return proto.CompactTextString(m) }
func (*Response_ReadFile) ProtoMessage()               {}
func (*Response_ReadFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 6} }

func (m *Response_ReadFile) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Response_ReadFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Contains full state of the agent i.e. information about the tasks,
// frameworks and executors running in the cluster.
type Response_GetState struct {
	GetTasks         *Response_GetTasks      `protobuf:"bytes,1,opt,name=get_tasks,json=getTasks" json:"get_tasks,omitempty"`
	GetExecutors     *Response_GetExecutors  `protobuf:"bytes,2,opt,name=get_executors,json=getExecutors" json:"get_executors,omitempty"`
	GetFrameworks    *Response_GetFrameworks `protobuf:"bytes,3,opt,name=get_frameworks,json=getFrameworks" json:"get_frameworks,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Response_GetState) Reset()                    { *m = Response_GetState{} }
func (m *Response_GetState) String() string            { return proto.CompactTextString(m) }
func (*Response_GetState) ProtoMessage()               {}
func (*Response_GetState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 7} }

func (m *Response_GetState) GetGetTasks() *Response_GetTasks {
	if m != nil {
		return m.GetTasks
	}
	return nil
}

func (m *Response_GetState) GetGetExecutors() *Response_GetExecutors {
	if m != nil {
		return m.GetExecutors
	}
	return nil
}

func (m *Response_GetState) GetGetFrameworks() *Response_GetFrameworks {
	if m != nil {
		return m.GetFrameworks
	}
	return nil
}

// Information about containers running on this agent. It contains
// ContainerStatus and ResourceStatistics along with some metadata
// of the containers.
type Response_GetContainers struct {
	Containers       []*Response_GetContainers_Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *Response_GetContainers) Reset()                    { *m = Response_GetContainers{} }
func (m *Response_GetContainers) String() string            { return proto.CompactTextString(m) }
func (*Response_GetContainers) ProtoMessage()               {}
func (*Response_GetContainers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 8} }

func (m *Response_GetContainers) GetContainers() []*Response_GetContainers_Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Response_GetContainers_Container struct {
	FrameworkId        *mesos.FrameworkID        `protobuf:"bytes,1,req,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	ExecutorId         *mesos.ExecutorID         `protobuf:"bytes,2,req,name=executor_id,json=executorId" json:"executor_id,omitempty"`
	ExecutorName       *string                   `protobuf:"bytes,3,req,name=executor_name,json=executorName" json:"executor_name,omitempty"`
	ContainerId        *mesos.ContainerID        `protobuf:"bytes,4,req,name=container_id,json=containerId" json:"container_id,omitempty"`
	ContainerStatus    *mesos.ContainerStatus    `protobuf:"bytes,5,opt,name=container_status,json=containerStatus" json:"container_status,omitempty"`
	ResourceStatistics *mesos.ResourceStatistics `protobuf:"bytes,6,opt,name=resource_statistics,json=resourceStatistics" json:"resource_statistics,omitempty"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *Response_GetContainers_Container) Reset()         { *m = Response_GetContainers_Container{} }
func (m *Response_GetContainers_Container) String() string { return proto.CompactTextString(m) }
func (*Response_GetContainers_Container) ProtoMessage()    {}
func (*Response_GetContainers_Container) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 8, 0}
}

func (m *Response_GetContainers_Container) GetFrameworkId() *mesos.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Response_GetContainers_Container) GetExecutorId() *mesos.ExecutorID {
	if m != nil {
		return m.ExecutorId
	}
	return nil
}

func (m *Response_GetContainers_Container) GetExecutorName() string {
	if m != nil && m.ExecutorName != nil {
		return *m.ExecutorName
	}
	return ""
}

func (m *Response_GetContainers_Container) GetContainerId() *mesos.ContainerID {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *Response_GetContainers_Container) GetContainerStatus() *mesos.ContainerStatus {
	if m != nil {
		return m.ContainerStatus
	}
	return nil
}

func (m *Response_GetContainers_Container) GetResourceStatistics() *mesos.ResourceStatistics {
	if m != nil {
		return m.ResourceStatistics
	}
	return nil
}

// Information about all the frameworks known to the agent at the current
// time.
type Response_GetFrameworks struct {
	Frameworks          []*Response_GetFrameworks_Framework `protobuf:"bytes,1,rep,name=frameworks" json:"frameworks,omitempty"`
	CompletedFrameworks []*Response_GetFrameworks_Framework `protobuf:"bytes,2,rep,name=completed_frameworks,json=completedFrameworks" json:"completed_frameworks,omitempty"`
	XXX_unrecognized    []byte                              `json:"-"`
}

func (m *Response_GetFrameworks) Reset()                    { *m = Response_GetFrameworks{} }
func (m *Response_GetFrameworks) String() string            { return proto.CompactTextString(m) }
func (*Response_GetFrameworks) ProtoMessage()               {}
func (*Response_GetFrameworks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 9} }

func (m *Response_GetFrameworks) GetFrameworks() []*Response_GetFrameworks_Framework {
	if m != nil {
		return m.Frameworks
	}
	return nil
}

func (m *Response_GetFrameworks) GetCompletedFrameworks() []*Response_GetFrameworks_Framework {
	if m != nil {
		return m.CompletedFrameworks
	}
	return nil
}

type Response_GetFrameworks_Framework struct {
	FrameworkInfo    *mesos.FrameworkInfo `protobuf:"bytes,1,req,name=framework_info,json=frameworkInfo" json:"framework_info,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Response_GetFrameworks_Framework) Reset()         { *m = Response_GetFrameworks_Framework{} }
func (m *Response_GetFrameworks_Framework) String() string { return proto.CompactTextString(m) }
func (*Response_GetFrameworks_Framework) ProtoMessage()    {}
func (*Response_GetFrameworks_Framework) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 9, 0}
}

func (m *Response_GetFrameworks_Framework) GetFrameworkInfo() *mesos.FrameworkInfo {
	if m != nil {
		return m.FrameworkInfo
	}
	return nil
}

// Lists information about all the executors known to the agent at the
// current time.
type Response_GetExecutors struct {
	Executors          []*Response_GetExecutors_Executor `protobuf:"bytes,1,rep,name=executors" json:"executors,omitempty"`
	CompletedExecutors []*Response_GetExecutors_Executor `protobuf:"bytes,2,rep,name=completed_executors,json=completedExecutors" json:"completed_executors,omitempty"`
	XXX_unrecognized   []byte                            `json:"-"`
}

func (m *Response_GetExecutors) Reset()                    { *m = Response_GetExecutors{} }
func (m *Response_GetExecutors) String() string            { return proto.CompactTextString(m) }
func (*Response_GetExecutors) ProtoMessage()               {}
func (*Response_GetExecutors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 10} }

func (m *Response_GetExecutors) GetExecutors() []*Response_GetExecutors_Executor {
	if m != nil {
		return m.Executors
	}
	return nil
}

func (m *Response_GetExecutors) GetCompletedExecutors() []*Response_GetExecutors_Executor {
	if m != nil {
		return m.CompletedExecutors
	}
	return nil
}

type Response_GetExecutors_Executor struct {
	ExecutorInfo     *mesos.ExecutorInfo `protobuf:"bytes,1,req,name=executor_info,json=executorInfo" json:"executor_info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Response_GetExecutors_Executor) Reset()         { *m = Response_GetExecutors_Executor{} }
func (m *Response_GetExecutors_Executor) String() string { return proto.CompactTextString(m) }
func (*Response_GetExecutors_Executor) ProtoMessage()    {}
func (*Response_GetExecutors_Executor) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 10, 0}
}

func (m *Response_GetExecutors_Executor) GetExecutorInfo() *mesos.ExecutorInfo {
	if m != nil {
		return m.ExecutorInfo
	}
	return nil
}

// Lists information about all the tasks known to the agent at the current
// time.
type Response_GetTasks struct {
	// Tasks that are pending in the agent's queue before an executor is
	// launched.
	PendingTasks []*mesos.Task `protobuf:"bytes,1,rep,name=pending_tasks,json=pendingTasks" json:"pending_tasks,omitempty"`
	// Tasks that are enqueued for a launched executor that has not yet
	// registered.
	QueuedTasks []*mesos.Task `protobuf:"bytes,2,rep,name=queued_tasks,json=queuedTasks" json:"queued_tasks,omitempty"`
	// Tasks that are running.
	LaunchedTasks []*mesos.Task `protobuf:"bytes,3,rep,name=launched_tasks,json=launchedTasks" json:"launched_tasks,omitempty"`
	// Tasks that are terminated but pending updates.
	TerminatedTasks []*mesos.Task `protobuf:"bytes,4,rep,name=terminated_tasks,json=terminatedTasks" json:"terminated_tasks,omitempty"`
	// Tasks that are terminated and updates acked.
	CompletedTasks   []*mesos.Task `protobuf:"bytes,5,rep,name=completed_tasks,json=completedTasks" json:"completed_tasks,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Response_GetTasks) Reset()                    { *m = Response_GetTasks{} }
func (m *Response_GetTasks) String() string            { return proto.CompactTextString(m) }
func (*Response_GetTasks) ProtoMessage()               {}
func (*Response_GetTasks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 11} }

func (m *Response_GetTasks) GetPendingTasks() []*mesos.Task {
	if m != nil {
		return m.PendingTasks
	}
	return nil
}

func (m *Response_GetTasks) GetQueuedTasks() []*mesos.Task {
	if m != nil {
		return m.QueuedTasks
	}
	return nil
}

func (m *Response_GetTasks) GetLaunchedTasks() []*mesos.Task {
	if m != nil {
		return m.LaunchedTasks
	}
	return nil
}

func (m *Response_GetTasks) GetTerminatedTasks() []*mesos.Task {
	if m != nil {
		return m.TerminatedTasks
	}
	return nil
}

func (m *Response_GetTasks) GetCompletedTasks() []*mesos.Task {
	if m != nil {
		return m.CompletedTasks
	}
	return nil
}

// Contains the agent's information.
type Response_GetAgent struct {
	SlaveInfo        *mesos.SlaveInfo `protobuf:"bytes,1,opt,name=slave_info,json=slaveInfo" json:"slave_info,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Response_GetAgent) Reset()                    { *m = Response_GetAgent{} }
func (m *Response_GetAgent) String() string            { return proto.CompactTextString(m) }
func (*Response_GetAgent) ProtoMessage()               {}
func (*Response_GetAgent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 12} }

func (m *Response_GetAgent) GetSlaveInfo() *mesos.SlaveInfo {
	if m != nil {
		return m.SlaveInfo
	}
	return nil
}

// Returns termination information about the nested container.
type Response_WaitNestedContainer struct {
	// Wait status of the lead process in the container. Note that this
	// is the return value of `wait(2)`, so callers must use the `wait(2)`
	// family of macros to extract whether the process exited cleanly and
	// what the exit code was.
	ExitStatus       *int32 `protobuf:"varint,1,opt,name=exit_status,json=exitStatus" json:"exit_status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response_WaitNestedContainer) Reset()         { *m = Response_WaitNestedContainer{} }
func (m *Response_WaitNestedContainer) String() string { return proto.CompactTextString(m) }
func (*Response_WaitNestedContainer) ProtoMessage()    {}
func (*Response_WaitNestedContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 13}
}

func (m *Response_WaitNestedContainer) GetExitStatus() int32 {
	if m != nil && m.ExitStatus != nil {
		return *m.ExitStatus
	}
	return 0
}

// *
// Streaming response to `Call::LAUNCH_NESTED_CONTAINER_SESSION` and
// `Call::ATTACH_CONTAINER_OUTPUT`.
//
// This message is also used to stream request data for
// `Call::ATTACH_CONTAINER_INPUT`.
type ProcessIO struct {
	Type             *ProcessIO_Type    `protobuf:"varint,1,opt,name=type,enum=agent.ProcessIO_Type" json:"type,omitempty"`
	Data             *ProcessIO_Data    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Control          *ProcessIO_Control `protobuf:"bytes,3,opt,name=control" json:"control,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ProcessIO) Reset()                    { *m = ProcessIO{} }
func (m *ProcessIO) String() string            { return proto.CompactTextString(m) }
func (*ProcessIO) ProtoMessage()               {}
func (*ProcessIO) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProcessIO) GetType() ProcessIO_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProcessIO_UNKNOWN
}

func (m *ProcessIO) GetData() *ProcessIO_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProcessIO) GetControl() *ProcessIO_Control {
	if m != nil {
		return m.Control
	}
	return nil
}

type ProcessIO_Data struct {
	Type             *ProcessIO_Data_Type `protobuf:"varint,1,opt,name=type,enum=agent.ProcessIO_Data_Type" json:"type,omitempty"`
	Data             []byte               `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ProcessIO_Data) Reset()                    { *m = ProcessIO_Data{} }
func (m *ProcessIO_Data) String() string            { return proto.CompactTextString(m) }
func (*ProcessIO_Data) ProtoMessage()               {}
func (*ProcessIO_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ProcessIO_Data) GetType() ProcessIO_Data_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProcessIO_Data_UNKNOWN
}

func (m *ProcessIO_Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProcessIO_Control struct {
	Type             *ProcessIO_Control_Type      `protobuf:"varint,1,opt,name=type,enum=agent.ProcessIO_Control_Type" json:"type,omitempty"`
	TtyInfo          *mesos.TTYInfo               `protobuf:"bytes,2,opt,name=tty_info,json=ttyInfo" json:"tty_info,omitempty"`
	Heartbeat        *ProcessIO_Control_Heartbeat `protobuf:"bytes,3,opt,name=heartbeat" json:"heartbeat,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ProcessIO_Control) Reset()                    { *m = ProcessIO_Control{} }
func (m *ProcessIO_Control) String() string            { return proto.CompactTextString(m) }
func (*ProcessIO_Control) ProtoMessage()               {}
func (*ProcessIO_Control) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ProcessIO_Control) GetType() ProcessIO_Control_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProcessIO_Control_UNKNOWN
}

func (m *ProcessIO_Control) GetTtyInfo() *mesos.TTYInfo {
	if m != nil {
		return m.TtyInfo
	}
	return nil
}

func (m *ProcessIO_Control) GetHeartbeat() *ProcessIO_Control_Heartbeat {
	if m != nil {
		return m.Heartbeat
	}
	return nil
}

type ProcessIO_Control_Heartbeat struct {
	Interval         *mesos.DurationInfo `protobuf:"bytes,1,opt,name=interval" json:"interval,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProcessIO_Control_Heartbeat) Reset()         { *m = ProcessIO_Control_Heartbeat{} }
func (m *ProcessIO_Control_Heartbeat) String() string { return proto.CompactTextString(m) }
func (*ProcessIO_Control_Heartbeat) ProtoMessage()    {}
func (*ProcessIO_Control_Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1, 0}
}

func (m *ProcessIO_Control_Heartbeat) GetInterval() *mesos.DurationInfo {
	if m != nil {
		return m.Interval
	}
	return nil
}

func init() {
	proto.RegisterType((*Call)(nil), "agent.Call")
	proto.RegisterType((*Call_GetMetrics)(nil), "agent.Call.GetMetrics")
	proto.RegisterType((*Call_SetLoggingLevel)(nil), "agent.Call.SetLoggingLevel")
	proto.RegisterType((*Call_ListFiles)(nil), "agent.Call.ListFiles")
	proto.RegisterType((*Call_ReadFile)(nil), "agent.Call.ReadFile")
	proto.RegisterType((*Call_LaunchNestedContainer)(nil), "agent.Call.LaunchNestedContainer")
	proto.RegisterType((*Call_WaitNestedContainer)(nil), "agent.Call.WaitNestedContainer")
	proto.RegisterType((*Call_KillNestedContainer)(nil), "agent.Call.KillNestedContainer")
	proto.RegisterType((*Call_RemoveNestedContainer)(nil), "agent.Call.RemoveNestedContainer")
	proto.RegisterType((*Call_LaunchNestedContainerSession)(nil), "agent.Call.LaunchNestedContainerSession")
	proto.RegisterType((*Call_AttachContainerInput)(nil), "agent.Call.AttachContainerInput")
	proto.RegisterType((*Call_AttachContainerOutput)(nil), "agent.Call.AttachContainerOutput")
	proto.RegisterType((*Response)(nil), "agent.Response")
	proto.RegisterType((*Response_GetHealth)(nil), "agent.Response.GetHealth")
	proto.RegisterType((*Response_GetFlags)(nil), "agent.Response.GetFlags")
	proto.RegisterType((*Response_GetVersion)(nil), "agent.Response.GetVersion")
	proto.RegisterType((*Response_GetMetrics)(nil), "agent.Response.GetMetrics")
	proto.RegisterType((*Response_GetLoggingLevel)(nil), "agent.Response.GetLoggingLevel")
	proto.RegisterType((*Response_ListFiles)(nil), "agent.Response.ListFiles")
	proto.RegisterType((*Response_ReadFile)(nil), "agent.Response.ReadFile")
	proto.RegisterType((*Response_GetState)(nil), "agent.Response.GetState")
	proto.RegisterType((*Response_GetContainers)(nil), "agent.Response.GetContainers")
	proto.RegisterType((*Response_GetContainers_Container)(nil), "agent.Response.GetContainers.Container")
	proto.RegisterType((*Response_GetFrameworks)(nil), "agent.Response.GetFrameworks")
	proto.RegisterType((*Response_GetFrameworks_Framework)(nil), "agent.Response.GetFrameworks.Framework")
	proto.RegisterType((*Response_GetExecutors)(nil), "agent.Response.GetExecutors")
	proto.RegisterType((*Response_GetExecutors_Executor)(nil), "agent.Response.GetExecutors.Executor")
	proto.RegisterType((*Response_GetTasks)(nil), "agent.Response.GetTasks")
	proto.RegisterType((*Response_GetAgent)(nil), "agent.Response.GetAgent")
	proto.RegisterType((*Response_WaitNestedContainer)(nil), "agent.Response.WaitNestedContainer")
	proto.RegisterType((*ProcessIO)(nil), "agent.ProcessIO")
	proto.RegisterType((*ProcessIO_Data)(nil), "agent.ProcessIO.Data")
	proto.RegisterType((*ProcessIO_Control)(nil), "agent.ProcessIO.Control")
	proto.RegisterType((*ProcessIO_Control_Heartbeat)(nil), "agent.ProcessIO.Control.Heartbeat")
	proto.RegisterEnum("agent.Call_Type", Call_Type_name, Call_Type_value)
	proto.RegisterEnum("agent.Call_AttachContainerInput_Type", Call_AttachContainerInput_Type_name, Call_AttachContainerInput_Type_value)
	proto.RegisterEnum("agent.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("agent.ProcessIO_Type", ProcessIO_Type_name, ProcessIO_Type_value)
	proto.RegisterEnum("agent.ProcessIO_Data_Type", ProcessIO_Data_Type_name, ProcessIO_Data_Type_value)
	proto.RegisterEnum("agent.ProcessIO_Control_Type", ProcessIO_Control_Type_name, ProcessIO_Control_Type_value)
}

func init() {
	proto.RegisterFile("github.com/miroswan/mesops/pkg/v1/agent/agent.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 2118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0xf1, 0xff, 0x93, 0xa2, 0x44, 0xb2, 0xf9, 0x21, 0x68, 0xf4, 0xb1, 0x5c, 0xac, 0xb7, 0xac, 0x95,
	0xff, 0x2e, 0x6b, 0x53, 0x59, 0x69, 0xad, 0xac, 0x1c, 0xa7, 0x9c, 0x43, 0x68, 0x12, 0xa2, 0x10,
	0xd1, 0xa4, 0x6b, 0x00, 0xc9, 0xeb, 0x5c, 0x58, 0x58, 0x72, 0x44, 0xa1, 0x0c, 0x02, 0x0c, 0x30,
	0x94, 0xe3, 0x1c, 0x73, 0x4f, 0xee, 0x79, 0x88, 0x54, 0x25, 0xa7, 0x5c, 0xf2, 0x04, 0x79, 0x81,
	0x9c, 0x93, 0x27, 0x48, 0x5e, 0x20, 0x95, 0x9a, 0x19, 0x0c, 0x3e, 0x08, 0x50, 0x6b, 0xfb, 0x90,
	0xca, 0x85, 0x35, 0xd3, 0xfd, 0xfb, 0xf5, 0xcc, 0x34, 0xa6, 0x7b, 0xba, 0x09, 0x3f, 0x9a, 0xda,
	0xf4, 0x66, 0xf1, 0xdd, 0xd1, 0xd8, 0x9b, 0x1d, 0xcf, 0x6c, 0xdf, 0x0b, 0xde, 0x5a, 0xee, 0xf1,
	0x8c, 0x04, 0xde, 0x3c, 0x38, 0x9e, 0xbf, 0x99, 0x1e, 0xdf, 0x3e, 0x3e, 0xb6, 0xa6, 0xc4, 0xa5,
	0xe2, 0xf7, 0x68, 0xee, 0x7b, 0xd4, 0x43, 0xeb, 0x7c, 0xa2, 0xbe, 0x07, 0x97, 0xcd, 0x02, 0xf1,
	0x2b, 0xb8, 0x07, 0x7f, 0xda, 0x81, 0x52, 0xc7, 0x72, 0x1c, 0xf4, 0xff, 0x50, 0xa2, 0xef, 0xe6,
	0xa4, 0x55, 0xd8, 0x2f, 0x1c, 0x36, 0x4f, 0x94, 0x23, 0xb1, 0x00, 0x53, 0x1d, 0x99, 0xef, 0xe6,
	0x04, 0x73, 0x2d, 0xfa, 0x31, 0xd4, 0xa6, 0x84, 0x8e, 0x66, 0x84, 0xfa, 0xf6, 0x38, 0x68, 0x15,
	0xf7, 0x0b, 0x87, 0xb5, 0x93, 0xbd, 0x24, 0xb8, 0x47, 0xe8, 0x0b, 0xa1, 0xc5, 0x30, 0x8d, 0xc6,
	0xa8, 0x07, 0x5b, 0x01, 0xa1, 0x23, 0xc7, 0x9b, 0x4e, 0x6d, 0x77, 0x3a, 0x72, 0xc8, 0x2d, 0x71,
	0x5a, 0x6b, 0x9c, 0xfe, 0x59, 0x92, 0x6e, 0x10, 0xda, 0x17, 0x98, 0x3e, 0x83, 0xe0, 0xcd, 0x20,
	0x2d, 0x40, 0xdf, 0x00, 0x38, 0x76, 0x40, 0x47, 0xd7, 0xb6, 0x43, 0x82, 0x56, 0x89, 0x5b, 0xd8,
	0x4d, 0x5a, 0xe8, 0xdb, 0x01, 0x3d, 0x63, 0x4a, 0x5c, 0x75, 0xe4, 0x10, 0x3d, 0x86, 0xaa, 0x4f,
	0xac, 0x09, 0x67, 0xb5, 0xd6, 0x39, 0x69, 0x27, 0x49, 0xc2, 0xc4, 0x9a, 0x30, 0x24, 0xae, 0xf8,
	0xe1, 0x08, 0xbd, 0x86, 0x4f, 0x1c, 0x6b, 0xe1, 0x8e, 0x6f, 0x46, 0x2e, 0x09, 0x28, 0x99, 0x8c,
	0xc6, 0x9e, 0x4b, 0x2d, 0xdb, 0x25, 0x7e, 0x6b, 0x83, 0x1b, 0xf8, 0x22, 0xb5, 0x2a, 0x87, 0x0e,
	0x38, 0xb2, 0x23, 0x81, 0x78, 0xd7, 0xc9, 0x13, 0x23, 0x03, 0x76, 0xdf, 0x5a, 0x36, 0xcd, 0x1a,
	0x2e, 0x73, 0xc3, 0xf7, 0x93, 0x86, 0x5f, 0x59, 0x36, 0x5d, 0x36, 0xbb, 0xfd, 0x36, 0x2b, 0x64,
	0x46, 0xdf, 0xd8, 0x8e, 0x93, 0x35, 0x5a, 0xc9, 0x1a, 0xbd, 0xb0, 0x1d, 0x27, 0x63, 0xf4, 0x4d,
	0x56, 0xc8, 0x9c, 0xe0, 0x93, 0x99, 0x77, 0x4b, 0xb2, 0x66, 0xeb, 0x59, 0x27, 0x60, 0x0e, 0xcd,
	0x38, 0xc1, 0xcf, 0x13, 0x23, 0x0f, 0xee, 0xaf, 0xf0, 0xef, 0x28, 0x20, 0x41, 0x60, 0x7b, 0x6e,
	0xab, 0xca, 0x97, 0x38, 0xfc, 0x5e, 0x3f, 0x1b, 0x02, 0x8f, 0xef, 0x39, 0x77, 0x68, 0xd1, 0x15,
	0xec, 0x59, 0x94, 0x5a, 0xe3, 0x9b, 0xc4, 0x4a, 0xb6, 0x3b, 0x5f, 0xd0, 0x16, 0xf0, 0x75, 0xf6,
	0x93, 0xeb, 0xb4, 0x39, 0x32, 0xb2, 0xa1, 0x33, 0x1c, 0xde, 0xb1, 0x72, 0xa4, 0xcc, 0x47, 0x19,
	0xbb, 0xde, 0x82, 0x32, 0xc3, 0xb5, 0xac, 0x8f, 0x96, 0x0c, 0x0f, 0x39, 0x10, 0xef, 0x5a, 0x79,
	0x62, 0xf5, 0x19, 0x40, 0x1c, 0x4f, 0xe8, 0x2b, 0x28, 0x53, 0x7b, 0x46, 0xbc, 0x05, 0xe5, 0x51,
	0x5a, 0x3b, 0xd9, 0x3e, 0x12, 0xa1, 0xdc, 0x5d, 0xf8, 0x16, 0xb5, 0x3d, 0x57, 0x77, 0xaf, 0x3d,
	0x2c, 0x31, 0xea, 0xb7, 0xb0, 0xb9, 0x14, 0x4d, 0x68, 0x07, 0xd6, 0x45, 0xe4, 0x15, 0xf6, 0x8b,
	0x87, 0x0d, 0x2c, 0x26, 0xe8, 0x18, 0x2a, 0x93, 0xd0, 0x42, 0xab, 0xb8, 0x5f, 0x5c, 0x65, 0x38,
	0x02, 0xa9, 0xf7, 0xa1, 0x1a, 0x45, 0x19, 0x42, 0x50, 0x9a, 0x5b, 0xf4, 0x86, 0x9b, 0xac, 0x62,
	0x3e, 0x56, 0x07, 0x50, 0x91, 0x11, 0x95, 0xa7, 0x47, 0x7b, 0xb0, 0xe1, 0x5d, 0x5f, 0x07, 0x84,
	0xf2, 0xf5, 0x4a, 0x38, 0x9c, 0x31, 0xb9, 0x43, 0xdc, 0x29, 0xbd, 0xe1, 0xa9, 0xa1, 0x84, 0xc3,
	0x99, 0xfa, 0xc7, 0x02, 0xec, 0xe6, 0x7e, 0x79, 0x74, 0x0a, 0xf5, 0xc4, 0xd7, 0x9c, 0xf0, 0x55,
	0x6a, 0x27, 0x28, 0xdc, 0x7f, 0xfc, 0xa5, 0xba, 0xb8, 0x16, 0xe1, 0xf4, 0x09, 0xfa, 0x21, 0x94,
	0xc7, 0xde, 0x6c, 0x66, 0xb9, 0x93, 0x30, 0x87, 0xc5, 0x0c, 0x2e, 0x15, 0x9e, 0x0c, 0x21, 0xe8,
	0x04, 0xaa, 0xf1, 0xbd, 0x5f, 0x0b, 0xb3, 0xc7, 0xf2, 0x0a, 0x8c, 0x11, 0xc3, 0xd4, 0x3e, 0x6c,
	0xe7, 0x84, 0xee, 0x47, 0xee, 0x57, 0x9d, 0xc0, 0x76, 0x4e, 0xcc, 0x7e, 0xec, 0xe9, 0xf7, 0x60,
	0x23, 0xb0, 0xa7, 0xae, 0xe5, 0xf0, 0xc3, 0xaf, 0xe3, 0x70, 0xa6, 0x0e, 0x60, 0x37, 0x37, 0x84,
	0x3f, 0x76, 0xd7, 0x7f, 0x2e, 0xc0, 0xbd, 0xbb, 0x02, 0xf6, 0x7f, 0xf7, 0xeb, 0xfd, 0xb3, 0x00,
	0x3b, 0x79, 0x29, 0x00, 0xfd, 0x24, 0xf5, 0x4c, 0x3e, 0xfc, 0xbe, 0x94, 0x91, 0x7c, 0x3b, 0x97,
	0x0f, 0xbb, 0xbc, 0xf5, 0x15, 0x87, 0x3d, 0x06, 0x98, 0xfb, 0xde, 0x98, 0x04, 0xc1, 0xc8, 0xf6,
	0xc2, 0xfd, 0xcb, 0xe7, 0xf9, 0xa5, 0x50, 0xe8, 0x43, 0x5c, 0x0d, 0x31, 0xba, 0x77, 0x70, 0x0a,
	0x25, 0xb6, 0x2a, 0xaa, 0x41, 0xf9, 0x72, 0x70, 0x31, 0x18, 0xbe, 0x1a, 0x28, 0xff, 0x87, 0x14,
	0xa8, 0x77, 0x86, 0x03, 0xb3, 0xad, 0x0f, 0x34, 0x3c, 0xd2, 0xbb, 0x4a, 0x01, 0x35, 0x01, 0x5e,
	0xe2, 0x61, 0x47, 0x33, 0x8c, 0x91, 0x3e, 0x54, 0x8a, 0xec, 0xe3, 0xe7, 0xe6, 0xa6, 0x8f, 0xfc,
	0x48, 0x07, 0x7f, 0x5b, 0xcb, 0xdb, 0x47, 0x13, 0xa0, 0xa7, 0x99, 0xa3, 0x73, 0xad, 0xdd, 0x37,
	0xcf, 0x95, 0x02, 0x6a, 0x40, 0x95, 0xcd, 0xcf, 0xfa, 0xed, 0x9e, 0xa1, 0x14, 0xd1, 0x26, 0xd4,
	0xd8, 0xf4, 0x4a, 0xc3, 0x86, 0x3e, 0x1c, 0x28, 0x6b, 0x52, 0xf0, 0x42, 0x33, 0xb1, 0xde, 0x31,
	0x94, 0x12, 0xda, 0x85, 0x2d, 0x26, 0xe8, 0x0f, 0x7b, 0x3d, 0x7d, 0xd0, 0x1b, 0xf5, 0xb5, 0x2b,
	0xad, 0xaf, 0xac, 0x33, 0xb1, 0x91, 0x11, 0x6f, 0xb0, 0xe5, 0xfa, 0xba, 0x61, 0x8e, 0xce, 0xf4,
	0xbe, 0x66, 0x28, 0x65, 0xb6, 0x1c, 0xd6, 0xda, 0x5d, 0x3e, 0x57, 0x2a, 0x72, 0x75, 0xc3, 0x6c,
	0x9b, 0x9a, 0x52, 0x45, 0x08, 0x9a, 0x6c, 0x1a, 0x39, 0xca, 0x50, 0x40, 0xca, 0xce, 0x70, 0xfb,
	0x85, 0xf6, 0x6a, 0x88, 0x2f, 0x0c, 0xa5, 0x86, 0xb6, 0xa0, 0xc1, 0x64, 0xda, 0xb7, 0x5a, 0xe7,
	0xd2, 0x1c, 0x62, 0x43, 0xa9, 0x4b, 0x4b, 0x66, 0xdb, 0xb8, 0x30, 0x94, 0x86, 0x9c, 0xb6, 0x7b,
	0xda, 0xc0, 0x54, 0x76, 0xd0, 0x67, 0xf0, 0x49, 0xbf, 0x7d, 0x39, 0xe8, 0x9c, 0x8f, 0x06, 0x9a,
	0x61, 0x6a, 0xdd, 0x78, 0x09, 0xa5, 0x89, 0x3e, 0x85, 0xdd, 0x57, 0x6d, 0xdd, 0xcc, 0xaa, 0x36,
	0x99, 0xea, 0x42, 0xef, 0xf7, 0xb3, 0x2a, 0x85, 0x99, 0xc4, 0xda, 0x8b, 0xe1, 0x95, 0x96, 0x55,
	0xee, 0xa2, 0x07, 0x70, 0x7f, 0xc5, 0x7a, 0x23, 0x43, 0x33, 0xb8, 0x6b, 0xb7, 0x90, 0x0a, 0x7b,
	0x6d, 0xd3, 0x6c, 0x77, 0xce, 0x13, 0x5a, 0x7d, 0xf0, 0xf2, 0xd2, 0x54, 0x10, 0xb3, 0x9e, 0xd1,
	0x0d, 0x2f, 0x4d, 0xa6, 0xdc, 0x3e, 0xf8, 0x43, 0x8b, 0xa5, 0xf7, 0x60, 0xee, 0xb9, 0x01, 0x41,
	0x87, 0xa9, 0x80, 0x90, 0x45, 0x95, 0x54, 0x27, 0xef, 0xff, 0x53, 0x60, 0x05, 0xe1, 0xe8, 0x86,
	0x58, 0x0e, 0xbd, 0x09, 0x6f, 0xff, 0xa7, 0xcb, 0xf8, 0x1e, 0xa1, 0xe7, 0x1c, 0x80, 0xab, 0x53,
	0x39, 0x44, 0xa7, 0xc0, 0x26, 0xa3, 0x6b, 0xc7, 0x9a, 0x06, 0x61, 0x04, 0xb4, 0x72, 0x88, 0x67,
	0x4c, 0x8f, 0x2b, 0xd3, 0x70, 0x84, 0x9e, 0x89, 0x62, 0xf5, 0x96, 0xf8, 0xbc, 0x9a, 0x10, 0xb5,
	0xa2, 0x9a, 0x43, 0xbc, 0x12, 0x08, 0x5e, 0xb0, 0x86, 0x63, 0x49, 0x96, 0x95, 0xee, 0xfa, 0x4a,
	0x72, 0x5e, 0xb5, 0x7b, 0x01, 0x5b, 0xd3, 0x4c, 0xb5, 0xbb, 0x91, 0xaa, 0xc3, 0x92, 0x26, 0xd2,
	0x15, 0xef, 0x74, 0xe9, 0xd1, 0x7e, 0x9a, 0xaa, 0x78, 0xcb, 0xf9, 0x7e, 0xcb, 0xad, 0x7a, 0x4f,
	0x93, 0x55, 0x6f, 0x25, 0xdf, 0x6f, 0x39, 0x95, 0x6f, 0xe8, 0xee, 0x80, 0x5a, 0x94, 0x84, 0x35,
	0x58, 0x9e, 0xbb, 0x0d, 0xa6, 0xe7, 0xee, 0xe6, 0x23, 0xd4, 0x85, 0x26, 0xa3, 0x45, 0x39, 0x20,
	0x08, 0xeb, 0xaa, 0xcf, 0x73, 0xb8, 0x51, 0xd6, 0x08, 0x70, 0x63, 0x9a, 0x9c, 0x4a, 0x2b, 0xd7,
	0xbe, 0x35, 0x23, 0x6f, 0x3d, 0xff, 0x4d, 0x10, 0x16, 0x51, 0x79, 0x56, 0xce, 0x22, 0x10, 0xb7,
	0x12, 0x4f, 0x51, 0x1b, 0x98, 0x60, 0x44, 0x7e, 0x45, 0xc6, 0x0b, 0xea, 0xf9, 0x41, 0x58, 0xad,
	0xde, 0xcb, 0x31, 0xa2, 0x49, 0x0c, 0xae, 0x4f, 0x13, 0x33, 0xe9, 0x05, 0x6a, 0x05, 0x6f, 0x82,
	0x56, 0x63, 0xa5, 0x17, 0x4c, 0xa6, 0xe7, 0x5e, 0xe0, 0x23, 0x49, 0xe3, 0xc0, 0xd6, 0xe6, 0x4a,
	0x5a, 0x9b, 0x49, 0x38, 0x8d, 0x8f, 0xd0, 0xab, 0x55, 0x2d, 0x41, 0x93, 0x9b, 0x78, 0xb0, 0x6c,
	0xe2, 0x7d, 0xdb, 0x02, 0xf5, 0x21, 0x54, 0xa3, 0x98, 0x42, 0x2d, 0x28, 0x8b, 0xf0, 0x7b, 0xc7,
	0xb3, 0x78, 0x05, 0xcb, 0xa9, 0xfa, 0x15, 0x54, 0x64, 0x04, 0xa1, 0x2f, 0x60, 0x5d, 0x84, 0x5a,
	0x61, 0x7f, 0xed, 0xb0, 0x76, 0x52, 0x0b, 0x33, 0x3d, 0x53, 0x62, 0xa1, 0x51, 0x3b, 0xbc, 0x30,
	0x95, 0xb1, 0x72, 0x0a, 0xf5, 0x30, 0xc8, 0x46, 0xb6, 0x7b, 0xed, 0x2d, 0xbd, 0x10, 0x21, 0x8a,
	0x3f, 0xb1, 0xb5, 0xdb, 0x78, 0xa2, 0x9e, 0xa6, 0xaa, 0xdb, 0x47, 0x50, 0x96, 0xc1, 0x26, 0xd6,
	0x6d, 0x84, 0x7c, 0x01, 0xc0, 0x52, 0xab, 0x3e, 0x82, 0xcd, 0xde, 0xfb, 0xd4, 0xb5, 0xea, 0xb3,
	0x64, 0x99, 0x7a, 0x04, 0xc0, 0xc2, 0x80, 0x6f, 0x50, 0xae, 0xb0, 0x29, 0x4f, 0x66, 0x3b, 0x44,
	0x54, 0x00, 0xd7, 0xe1, 0x28, 0x50, 0x4f, 0xd2, 0x25, 0x6c, 0x60, 0xff, 0x9a, 0x70, 0xeb, 0x25,
	0xcc, 0xc7, 0x4c, 0x36, 0xb1, 0xa8, 0xc5, 0x0b, 0xd8, 0x3a, 0xe6, 0x63, 0xf5, 0xaf, 0x05, 0xee,
	0x45, 0x11, 0x0e, 0xa9, 0xfb, 0x53, 0x78, 0xef, 0xfb, 0x93, 0xb9, 0xb9, 0xc5, 0x0f, 0xbe, 0xb9,
	0xd9, 0x10, 0x5a, 0xfb, 0xf0, 0x10, 0x52, 0xff, 0xb2, 0x06, 0x8d, 0x54, 0xa4, 0xa2, 0x1e, 0x40,
	0x22, 0xb8, 0x85, 0x0b, 0x1f, 0xdd, 0x19, 0xdc, 0x71, 0x75, 0x80, 0x13, 0x54, 0xf5, 0xef, 0x45,
	0xa8, 0xa6, 0x8a, 0xcb, 0x68, 0xab, 0xd9, 0xfa, 0x22, 0xda, 0x11, 0xab, 0x2f, 0x22, 0x9c, 0xce,
	0xca, 0xba, 0x9a, 0x74, 0x92, 0xa8, 0xa6, 0x18, 0x6b, 0x2b, 0x64, 0x49, 0x67, 0xe8, 0x5d, 0x0c,
	0x12, 0xa5, 0x4f, 0xd0, 0x03, 0x68, 0x44, 0x1c, 0xd7, 0x9a, 0x91, 0xd6, 0x1a, 0x6f, 0x4a, 0xea,
	0x52, 0x38, 0xb0, 0x66, 0xd9, 0x3a, 0xad, 0xf4, 0x7e, 0x45, 0x69, 0x1b, 0x94, 0x44, 0x07, 0x4b,
	0x2d, 0xba, 0x90, 0xaf, 0xc6, 0xde, 0x32, 0xd5, 0xe0, 0x5a, 0xbc, 0x39, 0x4e, 0x0b, 0xd0, 0xcf,
	0x61, 0xdb, 0x27, 0x81, 0xb7, 0xf0, 0xc7, 0x84, 0x5b, 0xb0, 0x03, 0xca, 0xc2, 0x61, 0x23, 0x4c,
	0xf9, 0xc2, 0x0a, 0x0e, 0x11, 0x46, 0x04, 0xc0, 0xc8, 0xcf, 0xc8, 0xd4, 0x7f, 0x17, 0xf8, 0xe7,
	0x4b, 0xe4, 0xc4, 0x1e, 0x40, 0xe2, 0x4a, 0xac, 0xfe, 0x7c, 0x31, 0x25, 0x76, 0x3e, 0x4e, 0x50,
	0xd1, 0x2f, 0x60, 0x67, 0xec, 0xcd, 0xe6, 0x0e, 0x61, 0x99, 0x2a, 0x61, 0xb2, 0xf8, 0x61, 0x26,
	0xb7, 0x23, 0x23, 0x89, 0x5b, 0x77, 0x0e, 0xd5, 0x68, 0x86, 0x9e, 0x41, 0x33, 0x71, 0x33, 0xe2,
	0xcc, 0xb2, 0x93, 0xb9, 0x1b, 0x2c, 0x78, 0x1b, 0xd7, 0xc9, 0xa9, 0xfa, 0xaf, 0x02, 0xd4, 0x93,
	0x41, 0x82, 0x3a, 0x50, 0x8d, 0xa3, 0x4a, 0x1c, 0xff, 0xe1, 0x5d, 0x51, 0x15, 0x5d, 0x22, 0x1c,
	0xf3, 0xd0, 0x15, 0xc4, 0xdb, 0x4e, 0x05, 0xe9, 0x07, 0x98, 0x43, 0x91, 0x85, 0x48, 0xa9, 0x76,
	0xa1, 0x22, 0x27, 0xe8, 0x69, 0xe2, 0x96, 0x26, 0x4e, 0xbd, 0xbd, 0x7c, 0xb7, 0xd9, 0xa1, 0xa3,
	0xab, 0xcb, 0xcf, 0xfc, 0xbb, 0x22, 0x4f, 0x40, 0x22, 0x93, 0x7c, 0x0d, 0x8d, 0x39, 0x71, 0x27,
	0xac, 0x00, 0x91, 0x49, 0x28, 0x99, 0xce, 0x19, 0x08, 0xd7, 0x43, 0x84, 0x60, 0x1c, 0x41, 0xfd,
	0x97, 0x0b, 0xb2, 0x20, 0x93, 0x90, 0x50, 0xcc, 0x12, 0x6a, 0x02, 0x20, 0xf0, 0x27, 0xd0, 0x14,
	0xff, 0xb8, 0x44, 0x8c, 0xb5, 0x2c, 0xa3, 0x21, 0x21, 0x82, 0xf3, 0x04, 0x14, 0x4a, 0xfc, 0x99,
	0xed, 0x5a, 0x34, 0x62, 0x95, 0xb2, 0xac, 0xcd, 0x18, 0x24, 0x78, 0xdf, 0xc0, 0x66, 0xec, 0x78,
	0x41, 0x5b, 0xcf, 0xd2, 0x9a, 0x11, 0x86, 0xb3, 0xd4, 0x67, 0xdc, 0x1f, 0xe2, 0x89, 0x3d, 0x06,
	0x08, 0x1c, 0xeb, 0x96, 0x48, 0x9f, 0x8a, 0x46, 0x4a, 0x90, 0x0d, 0xa6, 0x10, 0x4f, 0x40, 0x20,
	0x87, 0xea, 0x93, 0xfc, 0x16, 0xfe, 0x3e, 0x4b, 0x3c, 0x36, 0x95, 0x31, 0x5e, 0xe0, 0x2d, 0x34,
	0x30, 0x91, 0x08, 0xe3, 0x83, 0xdf, 0x16, 0xff, 0x9b, 0x9d, 0x4f, 0xba, 0xc5, 0xd9, 0x48, 0xb7,
	0x38, 0xe5, 0x74, 0x8b, 0x53, 0xc9, 0x69, 0x71, 0xaa, 0x39, 0x2d, 0x0e, 0x64, 0x5b, 0x9c, 0x5a,
	0xba, 0xc5, 0xa9, 0xa7, 0x5b, 0x9c, 0x3b, 0xba, 0x98, 0xc6, 0xc1, 0x3f, 0x4a, 0x50, 0x8d, 0x3a,
	0x55, 0xf4, 0x65, 0xaa, 0x61, 0xd8, 0x5d, 0xee, 0x64, 0x93, 0x1d, 0xc3, 0x97, 0xd1, 0x1b, 0x9b,
	0xfc, 0x97, 0x37, 0x86, 0x76, 0x2d, 0x6a, 0x89, 0xa7, 0x17, 0x9d, 0x40, 0x99, 0x65, 0x53, 0xdf,
	0x73, 0x96, 0x1a, 0x84, 0x18, 0xdd, 0x11, 0x7a, 0x2c, 0x81, 0xea, 0x6f, 0x0a, 0x50, 0x62, 0x26,
	0xd0, 0x51, 0x6a, 0x4b, 0x6a, 0xee, 0x3a, 0xc9, 0x7d, 0xa1, 0xc4, 0xbe, 0xc2, 0xb7, 0xff, 0xe0,
	0x49, 0xde, 0x37, 0xaf, 0xc2, 0xba, 0x61, 0x76, 0xf5, 0x81, 0x52, 0x40, 0x00, 0x1b, 0x86, 0xd9,
	0x1d, 0x5e, 0x9a, 0x4a, 0x31, 0x1c, 0x6b, 0x18, 0x2b, 0x6b, 0xea, 0xef, 0x8b, 0x50, 0x0e, 0x77,
	0x86, 0x1e, 0xa7, 0xf6, 0xf1, 0xf9, 0xaa, 0x13, 0xa4, 0x5d, 0x54, 0xa1, 0xf4, 0x9d, 0xb8, 0xd2,
	0xc2, 0x4d, 0x4d, 0x19, 0x0f, 0xe6, 0xeb, 0xf0, 0xff, 0x40, 0xfa, 0x8e, 0x0d, 0xd0, 0xcf, 0xa0,
	0x7a, 0x43, 0x2c, 0x9f, 0x7e, 0x47, 0x2c, 0x1a, 0x3a, 0xe9, 0x60, 0xe5, 0x12, 0xe7, 0x12, 0x89,
	0x63, 0x92, 0xfa, 0x53, 0xa8, 0x46, 0x72, 0x74, 0x0c, 0x15, 0xdb, 0xa5, 0xc4, 0xbf, 0xb5, 0x9c,
	0xbb, 0xfe, 0x8e, 0x8c, 0x40, 0x07, 0x5f, 0xe7, 0x79, 0xa8, 0x0e, 0x15, 0xd3, 0x7c, 0x3d, 0xd2,
	0x07, 0x67, 0x43, 0x11, 0x13, 0xe7, 0x5a, 0x1b, 0x9b, 0xcf, 0xb5, 0xb6, 0xa9, 0x14, 0x0f, 0x7e,
	0x90, 0xc7, 0xa8, 0x40, 0xa9, 0xdb, 0x36, 0xdb, 0x4a, 0x81, 0x89, 0xd9, 0x35, 0xc3, 0xc3, 0xbe,
	0x52, 0x7c, 0xbe, 0x0f, 0x7b, 0x9e, 0x3f, 0x3d, 0xb2, 0xe6, 0xd6, 0xf8, 0x86, 0x84, 0x1b, 0xe1,
	0x87, 0x7b, 0xbe, 0xf1, 0xd2, 0xf7, 0xa8, 0x17, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xd3,
	0xa1, 0x2a, 0x5c, 0x19, 0x00, 0x00,
}
